set nocompatible " must be first line
set encoding=utf-8
scriptencoding utf-8

filetype off
call plug#begin('~/.vim/bundle')


Plug 'altercation/vim-colors-solarized'
Plug 'dag/vim2hs'
Plug 'honza/vim-snippets'
Plug 'itchyny/calendar.vim'
Plug 'jceb/vim-orgmode'
Plug 'jiangmiao/auto-pairs'
Plug 'kalafut/vim-taskjuggler'
Plug 'kana/vim-textobj-user'
Plug 'kchmck/vim-coffee-script'
Plug 'kien/ctrlp.vim'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'mileszs/ack.vim'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'NLKNguyen/papercolor-theme'
Plug 'rking/ag.vim'
Plug 'scrooloose/syntastic'
Plug 'SirVer/ultisnips'
Plug 'sjl/gundo.vim'
Plug 'slim-template/vim-slim'
Plug 'sukima/xmledit'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-haml'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-rake'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'tyru/open-browser.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-ruby/vim-ruby'
Plug 'vim-scripts/dbext.vim'
Plug 'vim-scripts/gnuplot.vim'
Plug 'vim-scripts/tabular'
Plug 'vim-scripts/tlib'
Plug 'vim-scripts/vim-R-plugin'
Plug 'zaiste/tmux.vim'

"TODO
"Plug 'janko-m/vim-test'
call plug#end()

filetype plugin indent on " Automatically detect file types.
syntax on " syntax highlighting

set shortmess+=afilmnrxoOtT " abbrev. of messages (avoids 'hit enter')
set virtualedit=onemore " allow for cursor beyond last character
set history=1000 " Store a ton of history (default is 20)
"TODO-- save undo levels to disk"
set nospell " spell checking on

"! to be redo in coffee script syntax"
hi link coffeeSpaceError NONE
hi link coffeeSemicolonError NONE
hi link coffeeReservedError NONE
au BufNewFile, BufReadPost *.coffee setl foldmethod=indent nofoldenable
"!end"

"  no backups
set nobackup
set noswapfile
"au BufWinLeave * silent! mkview "make vim save view (state) (folds, cursor, etc)
"au BufWinEnter * silent! loadview "make vim load view (state) (folds, cursor, etc)


autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \ exe "normal g`\"" |
    \ endif

" colors 
set t_Co=256

set background=dark " Assume a dark background
colorscheme jellybeans
hi clear SpellBad
hi SpellBad cterm=undercurl
set tabpagemax=15 " only show 15 tabs
set title 
set visualbell " don't beep"
set noerrorbells " don't beep"

"statusline
set laststatus=2

set linespace=0 " No extra spaces between rows
set number " Line numbers on
set cursorline 
set cursorcolumn
set showmatch " show matching brackets/parenthesis
set incsearch " find as you type search
set nohlsearch " highlight search terms
set winminheight=0 " windows can be 0 line high
set fillchars+=vert:│  "Neat vertical window separator line
set ignorecase " case insensitive search
set smartcase " case sensitive when uc present
set wildmenu " show list instead of just completing
set wildignorecase " case insensitivity for the filename completion"
set wildmode=longest,list,full " command <Tab> completion, list matches, then longest common part, then all.
set wildignore+=*.pdf,*/tmp/*,*.so,*.swp,*.zip
set wildignore+=*.png
set wildignore+=*.jpg
set wildignore+=*.gif
set lazyredraw " redraw only when necessary
autocmd FileType help wincmd L " open help window in vertical split

" Exclude files and directories with ctrlp
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }

" Silver Searcher https://github.com/ggreer/the_silver_searcher
"TODO Speed up but remove the conditional
"TODO Create a script to check Vim dependencies so you don't check them every time
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag -Q -l --nocolor --hidden -g "" %s'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0 
endif


set whichwrap=b,s,h,l,<,>,[,] " backspace and cursor keys wrap to
set scrolljump=5 " lines to scroll when cursor leaves screen
set scrolloff=3 " minimum lines to keep above and below cursor
set gdefault " the /g flag on :s substitutions by default

set modeline 
set modelines=5

""--TODO: set magic=very
nnoremap / /\v
vnoremap / /\v
nnoremap ? /\v
vnoremap ? ?\v
cnoremap %s/ %s/\v


" Windows focus movements
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

"TODO: Navigation
" Switch between the last 2 files
nnoremap <leader><leader> <c-^>
map gl :buffers<CR>
map gb :bnext<CR>
map gB :bprev<CR>

" automatically resize windows 
autocmd vimResized * :wincmd =

" TODO: I need to spend some time to be comfortable with vim folds
" set foldenable " auto fold code

" Formatting 
set nowrap " wrap long lines
set autoindent " indent at the same level of the previous line
set shiftwidth=2 " use indents of 2 spaces
set expandtab " tabs are spaces, not tabs
set tabstop=2 " an indentation every two columns
"set softtabstop=2 " let backspace delete indent
set matchpairs+=<:> " match, to be used with %
"set pastetoggle=<F12> " pastetoggle (sane indentation on pastes)
let g:AutoPairs = {'(':')', '[':']', '{':'}',"'":"'",'"':'"', '`':'`'}

" Key (re)Mappings 
" Making it so ; works like : for commands. Saves typing and eliminates :W style typos due to lazy holding shift.
nnoremap ; :

" set digraph if working with French file

" when you forgot to sudo before editing a file
" cmap sw  w  !sudo tee % >/dev/null 

let mapleader=","
"quick edit/reload the vimrc file
nmap <silent> <leader>v :tabedit $MYVIMRC<CR>
nmap <silent> <leader>s :source $MYVIMRC<CR>

nmap <silent> <leader>b ysiw*<ESC>
nmap <silent> <leader>2b ebys2w*<ESC>
nmap <silent> <leader>3b ebys3w*<ESC>
nmap <silent> <leader>4b ebys4w*<ESC>
nmap <silent> <leader>5b ebys5w*<ESC>
nmap <silent> <leader>6b ebys6w*<ESC>
nmap <silent> <leader>p <c-p>

" copy the configuration of routers 
nmap <silent> <leader>r1 /R1\s*$<CR>yip<ESC>
nmap <silent> <leader>r2 /R2\s*$<CR>yip<ESC>
nmap <silent> <leader>r3 /R3\s*$<CR>yip<ESC>
nmap <silent> <leader>r4 /R4\s*$<CR>yip<ESC>
nmap <silent> <leader>r5 /R5\s*$<CR>yip<ESC>
nmap <silent> <leader>r6 /R6\s*$<CR>yip<ESC>
nmap <silent> <leader>r7 /R7\s*$<CR>yip<ESC>
nmap <silent> <leader>r8 /R8\s*$<CR>yip<ESC>
nmap <silent> <leader>r9 /R9\s*$<CR>yip<ESC>
nmap <silent> <leader>r10 /R10\s*$<CR>yip<ESC>
nmap <silent> <leader>s1 /S1\s*$<CR>yip<ESC>
nmap <silent> <leader>s2 /S2\s*$<CR>yip<ESC>
nmap <silent> <leader>s3 /S3\s*$<CR>yip<ESC>
nmap <silent> <leader>s4 /S4\s*$<CR>yip<ESC>


set ttyfast " send more characters for redraws"

"source vimrc each time I save it
if has("autocmd")
  autocmd bufwritepost .vimrc source $MYVIMRC
end

"edit list of abbreviations 
nmap <silent> <leader>a :tabedit ~/.vim/abbreviations.txt<CR>

set listchars=""
" Fuzzy Finder 
""" Fuzzy Find file, tree, buffer, line
"nmap <leader>ff :FufFile **/<CR>
"nmap <leader>ft :FufFile<CR>
"nmap <leader>fb :FufBuffer<CR>
"nmap <leader>fl :FufLine<CR>
"nmap <leader>fr :FufRenewCache<CR>

" dbext database plugin
" TODO: only for .sql files
"let g:dbext_default_profile = 'type=MYSQL:user=root:passwd=kyamukende:dbname=otrs:extra=-t'
let g:dbext_default_profile_ODBC = 'type=ODBC:dsnname=acdis:user=acapp_otrs:passwd=kyamukende:dbname=acdis'
let g:dbext_default_history_file = '~/.vim/dbext_sql_history.txt'
let g:dbext_default_PGSQL_cmd_terminator = ";"

source ~/.vim/abbreviations.txt

imap <F2>  <c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>
nmap <F2>  a<C-R>=strftime("%Y-%m-%d %a %H:%M")<CR><ESC>
imap <F3> <C-R>=strftime("%H%M")<CR>
nmap <F3> a<C-R>=strftime("%H%M")<CR><esc>
set clipboard=unnamed
vnoremap P <ESC>"+gP
nnoremap P <ESC>"+gP
nnoremap Y <ESC>"+y
vnoremap Y <ESC>"+y
set autowriteall " automatically write a file when leaving a modified buffer

" write with root permission
cmap w!! w !sudo tee % >/dev/null<CR>:e!<CR><CR>

" Gemmfile, Rakefile, Vagrantfile, Thorfile are Ruby"
au BufRead, BufNewFile {Gemfile,Gemfile.lock,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby
au BufRead, BufNewFile {*.asciidoc,*.adoc,*.ad} set ft= asciidoc

" enable compiler support for ruby
compiler ruby

" to be removed 
set maxmempattern=200000

"needed for ruby text objects
runtime macros/matchit.vim

" Ultisnips 
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsSnippetDirectories=["UltiSnips"]

set tags=./tags;

" Gundo
nnoremap <leader>u :GundoToggle<cr>
let g:gundo_close_on_revert=1

" Rails.vim 
"  :Rfea item
"TODO: Add this with projection
let g:rails_projections = { 
      \ "test/features/*_test.rb": { 
            \"command": "feature", 
            \ "template": "class %SDecorator < SimpleDelegator\nend", 
            \ "test": [ "test/features/%s" ],
            \ "affinity": "model" 
      \ }}


" Open browser
nmap <leader>w <Plug>(openbrowser-open)
vmap <leader>w <Plug>(openbrowser-open)

" utilities for Project Management
"TODO: create snipmate shortcut 
nmap <leader>ls olog start: "<c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>"<esc>
imap <leader>ls log start: "<c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>"
nmap <leader>lp olog pause: "<c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>"<esc>
imap <leader>lp log pause: "<c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>"
nmap <leader>lf olog finish: "<c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>"<esc>
imap <leader>lf log finish: "<c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>"
nmap <leader>lr olog resume: "<c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>"<esc>
imap <leader>lr log resume: "<c-r>=strftime("%Y-%m-%d %a %H:%M")<cr>"

" Airline
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
let g:airline_symbols.linenr = "|"
let g:airline_theme='zenburn'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
set guifont=Inconsolata\ for\ Powerline:h14
set noshowmode

" " Vim-test
" " To be combined with tslime 
" nnoremap <silent> <Leader>t :TestFile<CR>
" nnoremap <silent> <Leader>s :TestNearest<CR>
" nnoremap <silent> <Leader>l :TestLast<CR>
" nnoremap <silent> <Leader>a :TestSuite<CR>
" nnoremap <silent> <leader>=> :TestVisit<CR>
