AllCops:

  Include:
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/IndentArray:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/GuardClause:
  Enabled: false
